name: zonakasir
recipe: laravel
proxxy:
  web:
    - zonakasir.lndo.site
  web2:
    - admin.zonakasir.lndo.site
services:
  appserver:
    xdebug: false
  database:
    portforward: 5432
config:
  via: nginx
  php: '8.4'
  webroot: public
  composer_version: '2.2.12'
  database: postgres
