import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
  content: [
    // Laravel
    "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
    // App views & Filament resources
    "./resources/views/**/*.blade.php",
    "./app/Filament/**/*.php",
    // Filament vendor views (already in preset, but explicit for clarity)
    "./vendor/filament/**/*.blade.php",
    // Compiled Blade views (needed for dynamic classes generated by Filament components)
    "./storage/framework/views/*.php",
  ],

  theme: {
    extend: {
      fontFamily: {
        sans: ["Figtree", ...defaultTheme.fontFamily.sans],
      },
      colors: {
        lakasir: {
          primary: "#FF6600",
          secondary: "#1f2937",
        },
        zonakasir: {
          primary: "#FF6600",
          secondary: "#1f2937",
        },
      },
    },
  },

  plugins: [forms],
};
