import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

// Filament preset — available only after composer install (not on Vercel build)
let filamentPreset = {};
try {
  filamentPreset = require('./vendor/filament/support/tailwind.config.preset');
} catch {
  // vendor/ not available (Vercel build or fresh clone)
}

/** @type {import('tailwindcss').Config} */
export default {
  presets: [filamentPreset].filter(Boolean),
  content: [
    // Laravel
    "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
    // App views & Filament resources
    "./resources/views/**/*.blade.php",
    "./app/Filament/**/*.php",
    // Filament vendor views (already in preset, but explicit for clarity)
    "./vendor/filament/**/*.blade.php",
    // Compiled Blade views (needed for dynamic classes generated by Filament components)
    "./storage/framework/views/*.php",
  ],

  theme: {
    extend: {
      fontFamily: {
        sans: ["Figtree", ...defaultTheme.fontFamily.sans],
      },
      colors: {
        lakasir: {
          primary: "#FF6600",
          secondary: "#1f2937",
        },
        zonakasir: {
          primary: "#FF6600",
          secondary: "#1f2937",
        },
      },
    },
  },

  plugins: [forms],
};
