<?php

return [

    /*
    |--------------------------------------------------------------------------
    | On-Prem Mode
    |--------------------------------------------------------------------------
    |
    | When true, the app runs as a standalone on-prem installation (1 server,
    | 1 database, 1 tenant). Subscription/billing gates are bypassed and the
    | kasir always works. SaaS features (admin landlord, register self-serve,
    | payout) remain in codebase but are idle.
    |
    */
    'mode' => env('ONPREM_MODE', false),

    /*
    |--------------------------------------------------------------------------
    | License
    |--------------------------------------------------------------------------
    |
    | license_key      : generated by `php artisan onprem:license` on the vendor side
    | public_key       : vendor public key used to verify license signature locally
    | verify_command   : run locally, result cached; warning-only (kasir never blocked)
    |
    */
    'license' => [
        'key' => env('ONPREM_LICENSE_KEY'),
        'public_key' => env('ONPREM_PUBLIC_KEY'),
        'private_key' => env('ONPREM_PRIVATE_KEY'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Heartbeat (client -> vendor monitoring)
    |--------------------------------------------------------------------------
    |
    | url   : vendor endpoint, e.g. https://zonakasir.jogjatourdrive.com/api/v1/onprem/heartbeat
    | token : shared secret validated on vendor side
    | instance_id : generated once per deployment, stored in .env
    |
    | Heartbeat failure never affects local operation — silent fail, retry next day.
    |
    */
    'heartbeat' => [
        'url' => env('ONPREM_HEARTBEAT_URL'),
        'token' => env('ONPREM_HEARTBEAT_TOKEN'),
        'instance_id' => env('ONPREM_INSTANCE_ID'),
    ],

];
