<?php

return [
    'features' => [
        'pos' => 'Point of Sale (POS)',
        'pos_v2' => 'POS V2 (New UI)',
        'report' => 'Reports & Analytics',
        'stock_management' => 'Stock Management',
        'stock_opname' => 'Stock Opname',
        'member_management' => 'Member Management',
        'multi_store' => 'Multi Store',
        'api_access' => 'API Access',
        'export_csv' => 'Export CSV',
        'custom_print' => 'Custom Print',
        'product_import' => 'Product Import',
        'purchasing' => 'Purchasing',
        'receivable' => 'Receivable',
        'supplier' => 'Supplier Management',
        'voucher' => 'Voucher / Discount',
        'user_management' => 'User Management',
        'role_permission' => 'Role & Permission',
        'product_barcode' => 'Product Barcode',
        'product_sku' => 'Product SKU',
        'product_expired' => 'Product Expiry',
        'product_type' => 'Product Type',
        'product_initial_price' => 'Product Initial Price',
        'selling_tax' => 'Selling Tax',
        'print_selling_a5' => 'Print Selling A5',
        'print_product_label' => 'Print Product Label',
        'payment_shortcut' => 'Payment Shortcut',
        'total_revenue' => 'Total Revenue in Table',
        'edit_profile' => 'Edit Profile',
        'unlimited_products' => 'Unlimited Products',
        'unlimited_users' => 'Unlimited Users',
        'reports' => 'Reports & Analytics',
        'products' => 'Products Management',
        'users' => 'Users Management',
        'roles' => 'Roles & Permissions',
    ],
];
